parse_config:
  zmk_keycode_map:
    # Modifiers (short forms)
    LGUI: "‚åò"
    RGUI: "‚åò"
    LALT: "‚å•"
    RALT: "‚å•"
    LCTL: "‚åÉ"
    RCTL: "‚åÉ"
    LSFT: "‚áß"
    RSFT: "‚áß"
    # Modifiers (long forms)
    LEFT_GUI: "‚åò"
    RIGHT_GUI: "‚åò"
    LEFT_ALT: "‚å•"
    RIGHT_ALT: "‚å•"
    LEFT_CONTROL: "‚åÉ"
    RIGHT_CONTROL: "‚åÉ"
    LEFT_SHIFT: "‚áß"
    RIGHT_SHIFT: "‚áß"
    # Modifiers (alternate short forms)
    LCTRL: "‚åÉ"
    RCTRL: "‚åÉ"
    LSHFT: "‚áß"
    RSHFT: "‚áß"
    # Common keys
    TAB: "‚á•"
    ESC: "‚éã"
    BSPC: "‚å´"
    BACKSPACE: "‚å´"
    DEL: "‚å¶"
    DELETE: "‚å¶"
    ENT: "‚èé"
    RET: "‚èé"
    ENTER: "‚èé"
    RETURN: "‚èé"
    SPACE: "‚ê£"
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: "\\"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: "\""
    DQT: "\""
    COMMA: ","
    LESS_THAN: "<"
    LT: "<"
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    PIPE2: "|"
    # Keypad
    KP_MULTIPLY: "*"
    KP_DIVIDE: "/"
    KP_PLUS: "+"
    KP_MINUS: "-"
    KP_ENTER: "‚èé"
    # Numbers
    N0: "0"
    N1: "1"
    N2: "2"
    N3: "3"
    N4: "4"
    N5: "5"
    N6: "6"
    N7: "7"
    N8: "8"
    N9: "9"
    # Navigation
    UP: "‚Üë"
    DOWN: "‚Üì"
    LEFT: "‚Üê"
    RIGHT: "‚Üí"
    PGUP: "‚áû"
    PGDN: "‚áü"
    HOME: "‚§í"
    END: "‚§ì"
    # Bluetooth
    BT_CLR: "BT Clear"
    # Media
    VOLU: "üîä"
    VOLD: "üîà"
    MUTE: "üîá"
    PLAY_PAUSE: "‚èØ"
    PREV: "‚èÆ"
    NEXT: "‚è≠"
  modifier_fn_map:
    left_ctrl: "‚åÉ"
    right_ctrl: "‚åÉ"
    left_shift: "‚áß"
    right_shift: "‚áß"
    left_alt: "‚å•"
    right_alt: "‚å•"
    left_gui: "‚åò"
    right_gui: "‚åò"
    keycode_combiner: "{mods}+{key}"
    mod_combiner: "{mod_1}+{mod_2}"
